# Generated by Django 2.1.3 on 2018-11-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0002_auto_20181104_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keynivel', to='royale.Level'),
        ),
    ]
