# Generated by Django 2.1.3 on 2018-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0003_auto_20181105_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='detalle',
            field=models.CharField(help_text='Describa el tipo', max_length=200, verbose_name='Detalle'),
        ),
    ]
